[DEFAULT]
# GPIO pin for PIR sensor
GPIO_PIN=4

# Brightness values (0–255)
BRIGHTNESS_ON=255
BRIGHTNESS_DIM=20
BRIGHTNESS_OFF=0

# Timing (seconds)
DIM_AFTER=10
OFF_AFTER=20

LOOP_DELAY=1
FADE_STEP=5
FADE_DELAY=0.01
PRINT_LOGS=True

# Physical led notification engine.
DOT_SQUAD_ACTIVE=True
DOT_SQUAD_URL="http://localhost:4001"

# Backlight path
BRIGHTNESS_PATH=/sys/class/backlight/10-0045/brightness